title: Wei Shi's Homepage
page-top-title: Wei Shi
# top-section-bg-text: Computer Science
top-section-bg-text: CS&AI
home-subtitle: Wei Shi&ensp;|&ensp;史伟
copyright-text: '&copy; Wei Shi 2025. All Rights Reserved.'
